# channels.py
# Extracted from your NewPipe export on 2026-05-08
CHANNELS = [
    ("Ahmad Zeidabadi", "UCUycnksCaFu9-e2oRb6T9yw"),
    ("Arantik", "UCqiPfSQWNJenrTBAVCZVNow"),
    ("BBC Persian", "UCHZk9MrT3DGWmVqdsj5y0EA"),
    ("Car Wizard", "UC2TTf3i4wwsRW8ex1zRXH8A"),
    ("Chizomiz", "UCHy8QSSJ1gXu-zbDlwwsE-w"),
    ("Chris Titus Tech", "UCg6gPGh8HU2U01vaFCAsvmQ"),
    ("Doug DeMuro", "UCsqjHFMB_JYTaEnf_vmTNqg"),
    ("driving 4 answers", "UCwosUnVH6AINmxtqkNJ3Fbg"),
    ("DW Documentary", "UCW39zufHfsuGgpLviKh297Q"),
    ("DW فارسی", "UC8fNUW0nHyGxjLetxvJxn9g"),
    ("Engineering Explained", "UClqhvGmHcvWL9w3R48t9QXQ"),
    ("ExplainingComputers", "UCbiGcwDWZjz05njNPrJU7jA"),
    ("Fuse Podcast with Arash Nalchegar", "UCUPNsCvO1eZWhvdGJfT0wjA"),
    ("Hagerty", "UCLgEVx4mzk3T3mzgbKG54Eg"),
    ("Hamed Tavakoli", "UCO_emM0ykWiW0Q2Jtxei3NA"),
    ("Human David", "UCLJuIlvbrbJOaO6aT1dJIJA"),
    ("Level1Linux", "UCOWcZ6Wicl-1N34H0zZe38w"),
    ("Michael Tunnell", "UCmyGZ0689ODyReHw3rsKLtQ"),
    ("Moj Vahedi", "UCqngcLmyPqZwEfcjwMd_d-A"),
    ("Nick Spinelli", "UCvZc8_nKoSooYNpTC4dD22g"),
    ("OnTen", "UCEdjL1kbZ0K8nFu519vE5LQ"),
    ("Paul McGowan, PS Audio", "UC6mzA8J7n0ylf0RnDpj-vrg"),
    ("Practical Engineering", "UCMOqf8ab-42UUQIdVoKwjlQ"),
    ("Real Engineering", "UCR1IuLEqb6UEA_zQ81kwXfg"),
    ("The Car Care Nut", "UCEKt2bUDBoRUw3wpPpDOUaA"),
    ("The Car Care Nut Reviews", "UCUPPMkXFBPr-TAAE-CV9Jlg"),
    ("Ton Does Linux and More!", "UCUDdGb82Xsv4_LQprelLhqA"),
    ("WELT Documentary", "UCBAeFXaLV1ZqKqc-Uf3pKaA"),
    ("ار.اف.ای / RFI فارسی", "UCfN5syo6W8gR6FilalNqF-A"),
    ("مجتبی واحدی", "UCD_-CQZEcIgmwMA9msp0C2w"),
    ("مجله خلقت", "UCsMl-W1Ve2MwRhIWcSMjHiA"),
]
